# RASH-0.1 OS EDITION

import io
import builtins
import math
import urllib.request
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError
import time
import shutil

def check_url_exists(url, timeout=5):
    req = Request(url, method='HEAD')
    
    req.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)')
    
    try:
        with urlopen(req, timeout=timeout) as response:
            return response.status < 400
    except HTTPError as e:
        print(f"HTTP Error: {e.code}")
        return False
    except URLError as e:
        print(f"URL Error: {e.reason}")
        return False
    except Exception as e:
        print(f"Other Error: {e}")
        return False


PAOKET = "https://raw.githubusercontent.com/neel902/RASH-Paoket/refs/heads/main/packages/"

def col_print(lines, term_width=None, indent=0, pad=2):
    """Print list of strings in multiple columns
    Original: https://gist.github.com/critiqjo/2ca84db26daaeb1715e1
    Adjusted: https://gist.github.com/Nachtalb/8a85c0793b4bea0a102b7414be5888d4
    """
    if not term_width:
        size = shutil.get_terminal_size((80, 20))
        term_width = size.columns

    n_lines = len(lines)
    if n_lines == 0:
        return

    col_width = max(len(line) for line in lines)
    n_cols = int((term_width + pad - indent) / (col_width + pad))
    n_cols = min(n_lines, max(1, n_cols))

    col_len = int(n_lines / n_cols) + (0 if n_lines % n_cols == 0 else 1)
    if (n_cols - 1) * col_len >= n_lines:
        n_cols -= 1

    cols = [lines[i * col_len: i * col_len + col_len] for i in range(n_cols)]

    rows = list(zip(*cols))
    rows_missed = zip(*[col[len(rows):] for col in cols[:-1]])
    rows.extend(rows_missed)

    for row in rows:
        printf(" " * indent + (" " * pad).join(line.ljust(col_width) for line in row))


def pull_url(url):
    try:
        with urllib.request.urlopen(urllib.request.Request(url + f"?t={int(time.time())}")) as response:
            file_contents = response.read().decode('utf-8')
        return file_contents
    except Exception as e:
        raise UsrError(str(e))

def base64(num):
    BASE64_ALPHABET = " !\"#\\$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_abcdefghijklmnopqrstuvwxyz{|}~`00000000"
    if num == 0:
        return BASE64_ALPHABET[0]
    
    arr = []
    base = 99
    while num:
        num, rem = divmod(num, base)
        arr.append(BASE64_ALPHABET[rem])
        
    return ''.join(reversed(arr))
def base10(b64_str):
    BASE64_ALPHABET = " !\"#\\$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_abcdefghijklmnopqrstuvwxyz{|}~`00000000"
    CHAR_TO_INDEX = {char: index for index, char in enumerate(BASE64_ALPHABET)}
    num = 0
    for char in b64_str:
        num = num * 99 + CHAR_TO_INDEX[char]
    return num

def printf(*args, end2="\n"):
    """Prints to the console."""
    print(*args, end=end2)

def printe(msg):
    """Prints as an error message to the console."""
    print("\033[91m" + msg + "\033[0m")

class UsrError(Exception):
    """Custom exception for user errors."""
    pass

PASSWORD = "rash2026"
USR = "rashuser"

WELCOME_MSG = "\x1b[1;34;44m"+r"""
 _    _  ____  __    ___  _____  __  __  ____    ____  _____        
( \/\/ )( ___)(  )  / __)(  _  )(  \/  )( ___)  (_  _)(  _  )       
 )    (  )__)  )(__( (__  )(_)(  )    (  )__)     )(   )(_)(        
(__/\__)(____)(____)\___)(_____)(_/\/\_)(____)   (__) (_____)       
 ____    __    ___  _   _       ___  __    ___   ___  ___    _      
(  _ \  /__\  / __)( )_( )___  / _ \/  )  (__ \ / _ \(__ \  / )     
 )   / /(__)\ \__ \ ) _ ((___)( (_) ))(    / _/( (_) )/ _/ / _ \    
(_)\_)(__)(__)(___/(_) (_)     \___/(__)  (____)\___/(____)\___/    
RiverCape Advanced Shell for the RSIE (OS Edition)
"""+"\033[0m"

MEMORY = 8192

PERMS = False

CURR_DIR = "/"

class ROM:
    def paoket(flags, ram):
        if len(flags) > 0:
            url = PAOKET + (flags[0] if flags[0].endswith(".py") else flags[0] + ".py")
            package_path = PAOKET + (flags[0] if flags[0].endswith(".py") else flags[0] + ".py") + ".meta"
            pckgmeta = pull_url(package_path)
            #print(pckgmeta)
            metadata = {}
            exec(pckgmeta, globals=metadata)
            pckgloc = metadata["location"]
            pckgloc2 = metadata["otherloc"]
            pckver = metadata["version"]
            metadata.clear()
            printf(f"Installing {flags[0].replace(".py", "")}-{pckver}")
            pack = pull_url(url)
            FileAPI.set_file(pckgloc, pack)
            for loc in pckgloc2:
                FileAPI.set_file(loc, "Welcome! (Auto generated by paoket)")

            FileAPI.set_file("/paoket/packages/packages.txt", (FileAPI.get_file("/paoket/packages/packages.txt") if FileAPI.file_exists("/paoket/packages/packages.txt") else "") + f"\n{flags[0].replace(".py", "")} | {pckver} | {package_path}")
            printf(f"Finished installing {flags[0].replace(".py", "")}-{pckver}")
        else:
            if not FileAPI.file_exists("/paoket/packages/packages.txt"):
                printf("No packages installed or malformed packages.txt")
            else:
                package_list = FileAPI.get_file("/paoket/packages/packages.txt").split("\n")
                packages = []
                for line in package_list:
                    if line.strip() == "":
                        continue
                    else:
                        packages.append(line.split("|")[0].strip() + "-" + line.split("|")[1].strip())
                col_print(packages)
        return ram
    def paoketinfo(flags, ram):
        if len(flags) > 0:
            url = PAOKET + (flags[0] if flags[0].endswith(".py") else flags[0] + ".py") + ".txt"
            print(pull_url(url))
        return ram
    def ed(flags, ram):
        if len(flags) > 0:
            file = (CURR_DIR + flags[0][1:]) if flags[0].startswith("/") else (CURR_DIR + flags[0])
            contents = FileAPI.get_file(file)
            app = FileEd.create_editor_app(initial_text=contents, file_name=file if "." in file else file + ".txt")
            FileAPI.set_file(file, app.run())
            printf("Finished ed command")
        else:
            raise UsrError("Note nough arguments for ed command")
        return ram
    def read(flags, ram):
        if len(flags) > 0:
            printf(FileAPI.get_file(((CURR_DIR + flags[0][1:]) if flags[0].startswith("/") else (CURR_DIR + flags[0]))))
            """addr = int(flags[0])
            if 0 <= addr < MEMORY:
                printf(base64(ram[addr]) if "--text" in flags else ram[addr])
            else:
                raise UsrError(f"Address {addr} is out of bounds (0-{MEMORY-1})")"""
        else:
            raise UsrError("Not enough arguments for read command")
        return ram
    def rm(flags, ram):
        if len(flags) > 0:
            if input(f"Are you sure you want to delete {(((CURR_DIR + flags[0][1:]) if flags[0].startswith("/") else (CURR_DIR + flags[0])))}? This action cannot be undone. Type 'yes' to confirm: ") == 'yes':
                FileAPI.delete_file(((CURR_DIR + flags[0][1:]) if flags[0].startswith("/") else (CURR_DIR + flags[0])))
            else:
                printf("Operation cancelled")
        else:
            raise UsrError("Not enough arguments for remove command")
        return ram
    def write(flags, ram):
        printe("Warning: The 'write' command is deprecated. Please use 'ed' or 'edit'. No file changes have been made.")
        return ram
        if len(flags) > 1:
            printe("Warning: The 'write' command is deprecated. Please use 'ed' or 'edit'. No file changes have been made.")
            #FileAPI.set_file(CURR_DIR + flags[0][1:] if flags[0].startswith("/") else (CURR_DIR + flags[0]), " ".join(flags[1:]))
            """addr = int(flags[0])
            value = int(base10(" ".join(flag for flag in flags[1:] if not flag.startswith("--")))) if "--text" in flags else flags[1]
            if 0 <= addr < MEMORY:
                ram[addr] = value
            else:
                raise UsrError(f"Address {addr} is out of bounds (0-{MEMORY-1})")"""
        else:
            raise UsrError("Not enough arguments for write command")
        return ram
    def cd(flags, ram):
        global CURR_DIR
        if len(flags) > 0:
            new_dir = flags[0]
            if new_dir.startswith("/"):
                CURR_DIR = new_dir
            else:
                CURR_DIR = CURR_DIR.rstrip("/") + "/" + new_dir
            if not CURR_DIR.endswith("/"):
                CURR_DIR += "/"
        else:
            raise UsrError("Not enough arguments for cd command")
        return ram
    def current_directory(flags, ram):
        printf(CURR_DIR)
        return ram
    def ls(flags, ram):
        if len(flags) > 0:
            dir_path = flags[0]
            if not dir_path.startswith("/"):
                dir_path = CURR_DIR.rstrip("/") + "/" + dir_path
        else:
            dir_path = CURR_DIR
        
        content = FileAPI.list_files_in_directory(dir_path)
        if content is not None:
            col_print(content)
        else:
            raise UsrError(f"Directory {dir_path} does not exist")
        
        return ram
    def testconsole(flags, ram):
        printf("Message test")
        return ram
    def help(flags, ram):
        if len(flags) > 0:
            command = flags[0]
            if command == "exit":
                printf("Exits the program. Usage: exit")
            elif command == "sjelter":
                printf("Sjelter? Usage: sjelter")
            elif command in ROM.alias:
                printf(ROM.helpmsg[ROM.alias[command]])
                # Add more detailed help for each command as needed
            else:
                raise UsrError(f"No help available for unknown command '{command}'")
        else:
            printf("Available commands:")
            col_print((list(ROM.pin.keys())) + ["exit", "sjelter"])
            printf("\nType 'help <command>' for more details on a specific command.")
        return ram
    def clearconsole(flags, ram):
        printf("\033[2J\033[3J\033[H")  # ANSI escape code to clear the console
        return ram
    def aliases(flags, ram):
        command = flags[0] if len(flags) > 0 else None
        if command in ROM.alias.keys():
            printf(f"Alias for '{command}': {', '.join([key for key, value in ROM.alias.items() if value == ROM.alias[command]])}")
        else:
            printf(f"No alias found for '{command}'")
        return ram
    def echo(flags, ram):
        printf(" ".join(flags))
        return ram
    def typeCONSOLEVER(flags, ram):
        if len(flags) > 0:
            if flags[0] == "exit":
                printf("Command 'exit' is a built-in command.")
            elif flags[0] == "sjelter":
                printf("Sjelter? Command 'sjelter' is a built-in command.")
            elif flags[0] in ROM.alias:
                printf(f"Command '{flags[0]}' is an alias for '{ROM.alias[flags[0]]}'.")
            else:
                printf(f"Command '{flags[0]}' is not recognized.")
        else:
            raise UsrError("Not enough arguments for type command")
        return ram
    def math(flags, ram):
        if len(flags) > 0:
            try:
                expression = " ".join(flags)
                result = eval(expression, {"__builtins__": None}, {"math": math})
                printf(f"Result: {result}")
            except Exception as e:
                raise UsrError(f"Error evaluating expression: {e}")
        else:
            raise UsrError("Not enough arguments for math command")
        return ram
    def pythonCONSOLEVER(flags, ram):
        oldram = ram.copy()
        variables = {}
        
        class rash:
            def __init__(self):
                printf("RASH Python console. Use rash.merge(address, value) to write to memory, rash.get(address) to read from memory, and rash.rollback() to revert changes.")
            def merge(adr,val):
                ram[int(adr)] = val
            def get(adr):
                return ram[int(adr)]
            def rollback():
                nonlocal ram
                ram = oldram.copy()
        class rashFS:
            def read(path):
                return FileAPI.get_file(path)
            def write(path, value):
                FileAPI.set_file(path, value)
            def delete(path):
                FileAPI.delete_file(path)
    

        def openOVERRIDE(path, type):
            printe("Do not use 'open' in the RASH terminal. Instead, use rashFS.")
            return io.StringIO(FileAPI.get_file(path))
        
        variables['rash'] = rash
        variables['open'] = openOVERRIDE
        variables['rashFS'] = rashFS
        if len(flags) == 0:
            
            running2 = True
            print("Entering Python console. Type 'exit()' to return to the main console. This will not stop RASH.")
            while running2:
                try:
                    user_input2 = input("Python> ")
                    if user_input2.lower() == 'exit()':
                        running2 = False
                        printf("Exiting Python console...")
                    else:
                        exec(user_input2, globals=variables)
                except Exception as e:
                    printe(f"Error: {e}")
        else:
            code = FileAPI.get_file(((CURR_DIR + flags[0][1:]) if flags[0].startswith("/") else (CURR_DIR + flags[0])))
            if code == "\033[91mUNKNOWN FILE\033[0m": raise UsrError("Unknown / invalid python file")
            exec(code,globals=variables)
        return ram
    def sudo(flags, ram):
        if (flags) == (["rm", "rf", "--no-preserve-root", "/"]):
            raise UsrError("Uninstalling french language pack... Please do not attempt to delete root directory during this process.")
        elif (flags) == (["rm", "rf", "/"]):
            raise UsrError("Use --no-preserve-root to uninstall french language pack. Please do not attempt to delete root directory during this process.")
        elif len(flags) > 0:
            password = flags[0]
            global PASSWORD
            global PERMS
            if password == PASSWORD:
                printf("\033[F\033[KPassword Hidden\nPermissions succesfully elevated." if not PERMS else "\033[F\033[KPassword Hidden\nPermissions already elevated.")
                PERMS = True
            elif password == "password" and PERMS:
                if len(flags) > 1 and flags[1] == "reset":
                    PASSWORD = "rash2026"
                if len(flags) > 1 and flags[1] == "get":
                    printf(f"Current password: {PASSWORD}")
                if len(flags) > 2 and flags[1] == "set":
                    PASSWORD = flags[2]
            elif password == "off":
                printf("Permissions succesfully revoked." if PERMS else "Permissions already revoked.")
                PERMS = False
            else:
                raise UsrError("Incorrect password for sudo command")
        else:
            raise UsrError("Not enough arguments for sudo command")

        return ram
    def rashfetch(flags, ram):
        T1=r"""
[2;34m         _       [0m
[2;34m        /\ \     [0m
[2;34m       /  \ \    [0m
[2;34m      / /\ \ \   [0m
[2;34m     / / /\ \ \  [0m
[2;34m    / / /  \ \_\ [0m
[2;34m   / / /   / / / [0m
[2;34m  / / /   / / /  [0m
[2;34m / / /___/ / /   [0m
[2;34m/ / /____\/ /    [0m
[2;34m\/_________/     [0m
                 
                 
                 
                 
                 
                 

"""
        T2 = ("""
[2;34m[1;34m   ___    _    ___  _ __     _    _
[2;34m[1;34m  / o | .' \ ,' _/ /// /   ,' \ ,'/[0m[2;34m
[2;34m[1;34m /  ,' / o /_\ `. / ` /___/ 0 / // [0m[2;34m
[2;34m[1;34m/_/`_\/_n_//___,'/_n_//__/\_,' //  [0m[2;34m
                                   [0m

[2;34m[0m[1;2m[1;34mTerminal:[0m [0m       Rash Integrated Terminal[1;2m[1;34m[0m
[2;34m[0m[1;2m[1;34mShell:[0m[0m[2;34m [0m          RASH-01[0m
[2;34m[1;34m[1;34mRAM Usage:[0m[1;34m[0m[2;34m [0m      ${1}kb/${2}kb[0m
[1;2m[1;34mOS:[0m[0m[2;34m[0m              Rash Sandboxing Interface Extended (RSIE)[0m
[2;34m[0m[1;2m[1;34mKernel:[0m[0m          Rash Sandboxing Interface Extended (RSIE)[2;34m[0m
[0m[1;2m[1;34mUser: [0m[0m           rash2026[2;34m[0m
[0m[1;2m[1;34mCPU: [0m[0m            Rash Sandboxing Interface Extended (RSIE)[0m
[2;34m[0m[1;2m[1;34mGPU:[0m[0m             Rash Sandboxing Interface Extended (RSIE)[0m
""".replace("${1}", str(sum(1/1024 for x in ram if x != 0))).replace("${2}", str(MEMORY/1024)))
        T = (t1+t2 for t1,t2 in zip(T1.splitlines(),T2.splitlines()))
        printf("\n".join(T))

        return ram
    def format(flags, ram):
        if len(flags) > 0:
            if flags[0] == "drive":
                if input("Are you sure you want to format the drive? This will erase all data. Type 'yes' to confirm: ") == "yes":
                    FileAPI.format_drive()
                    global CURR_DIR
                    CURR_DIR = "/"
                    printf("Drive formatted successfully.")
                else:
                    printf("Format operation cancelled.")
            else:
                raise UsrError(f"Unknown format target '{flags[0]}'. Currently, only 'drive' is supported.")
        else:
            raise UsrError("Not enough arguments for format command")
        return ram
    def drive_details(flags, ram):
        printf("\n".join(f"{list(FileAPI.drive_details().keys())[j]:15}|{FileAPI.drive_details()[list(FileAPI.drive_details().keys())[j]]:>15}" for j in range(len(FileAPI.drive_details().items()))))
        return ram
    def create(flags, ram):
        FileAPI.set_file(CURR_DIR + flags[0][1:] if flags[0].startswith("/") else (CURR_DIR + flags[0]), "Welcome")
        return ram
    def run(flags, ram):
        if len(flags) > 0:
            path = "/paoket/packages/" + flags[0] + ("" if flags[0].endswith(".py") else ".py")
            if FileAPI.file_exists(path):
                oldram = ram.copy()
                variables = {}
                
                class rash:
                    def __init__(self):
                        printf("RASH Python console. Use rash.merge(address, value) to write to memory, rash.get(address) to read from memory, and rash.rollback() to revert changes.")
                    def merge(adr,val):
                        nonlocal ram
                        ram[int(adr)] = val
                    def get(adr):
                        return ram[int(adr)]
                    def rollback():
                        nonlocal ram
                        ram = oldram.copy()
                class rashFS:
                    def read(path):
                        return FileAPI.get_file(path)
                    def write(path, value):
                        FileAPI.set_file(path, value)
                    def delete(path):
                        FileAPI.delete_file(path)
                
                
                def openOVERRIDE(path, type):
                    printe("Error in package: Message: Do not use 'open' in the RASH terminal. Instead, use rashFS. Please contact the package owner to change this.")
                    return io.StringIO(FileAPI.get_file(path))
                
                variables['rash'] = rash
                variables['open'] = openOVERRIDE
                variables['rashFS'] = rashFS
                
                code = FileAPI.get_file(path)
                exec(code,globals=variables)
            else:
                url = PAOKET + (flags[0] if flags[0].endswith(".py") else flags[0] + ".py")
                exists = check_url_exists(url)
                raise UsrError(f"Package {flags[0]} does not exist, but can be downloaded with paoket {flags[0]}." if exists else f"Package {flags[0]} does not exist.")
        else:
            raise UsrError("Not enough arguments for run command")
        return ram
    def paoketupdate(flags, ram):
        if not FileAPI.file_exists("/paoket/packages/packages.txt"):
            raise (UsrError("No packages to update or malformed packages.txt file."))
        else:
            package_list = FileAPI.get_file("/paoket/packages/packages.txt").split("\n")
            newfile = ""
            for line in package_list:
                if line.strip() == "":
                    continue
                else:
                    lines = line.strip().split("|")
                    if len(lines) < 3 : raise UsrError("Malformed packages.txt file.")
                    printf(f"Found existing package {lines[0].strip()} on version {lines[1].strip()}. Checking for updates...")
                    pckgmeta = pull_url(lines[2])
                    metadata = {}
                    exec(pckgmeta, globals=metadata)
                    pckgloc = metadata["location"]
                    pckgloc2 = metadata["otherloc"]
                    pckver = metadata["version"]
                    metadata.clear()
                    if pckver.strip() == lines[1].strip():
                        printf("No updates found. Continuing.")
                        newfile += line + "\n"
                        continue
                    else:
                        printf(f"New version found: {pckver}. Installing... [....]", end2="")
                        url = lines[2].strip().removesuffix(".meta")
                        package = pull_url(url)
                        FileAPI.set_file(pckgloc, package)
                        for loc in pckgloc2:
                            FileAPI.set_file(loc, "Welcome! (Auto generated by paoket)")
            
                        newfile += f"\n{lines[0].strip()} | {pckver} | {lines[2].strip()}"
                        printf(f"\rNew version found: {pckver}. Installing... [\033[32mDONE\033[0m]")
            FileAPI.set_file("/paoket/packages/packages.txt", newfile)
        return ram

    NEEDS_ELEVATED_PERMS = ["python", "format", "rm", "ed", "paoket"]
    pin = {
        "read": read,
        "write": write,
        "testconsole": testconsole,
        "help": help,
        "clearconsole": clearconsole,
        "aliases": aliases,
        "echo": echo,
        "type": typeCONSOLEVER,
        "math": math,
        "python": pythonCONSOLEVER,
        "sudo": sudo,
        "rashfetch": rashfetch,
        "cd": cd,
        "ls": ls,
        "current_directory": current_directory,
        "format": format,
        "rm": rm,
        "drive_details": drive_details,
        "ed": ed,
        "create": create,
        "paoket": paoket,
        "run": run,
        "paoketinfo": paoketinfo,
        "paoketupdate": paoketupdate
    }
    helpmsg = {
        "read": "Reads a file. Usage: read <file path>",
        "testconsole": "Tests the console output. Usage: testconsole",
        "help": "Displays help information for commands. Usage: help [command]",
        "clearconsole": "Clears the console. Usage: clearconsole",
        "aliases": "Displays aliases for commands. Usage: aliases [command]",
        "echo": "Echoes the input back to the console. Usage: echo <message>",
        "type": "Returns the type of a command. Usage: type <command>",
        "math": "Evaluates a mathematical expression. Usage: math <expression>",
        "python": "Enters a Python console or executes Python code. Usage: python [address]",
        "sudo": "Elevates permissions for the session. Usage: sudo <password>|password [reset|get|set] [<new_password>|off]",
        "rashfetch": "Displays system information. Usage: rashfetch",
        "cd": "Changes the current directory. Usage: cd <directory>",
        "ls": "Lists the contents of a directory. Usage: ls [directory]",
        "current_directory": "Displays the current directory. Usage: pwd (if you use current_directory here, you will be banned from the RASH discord server (note: does not exist yet))",
        "format": "Formats the drive. Usage: format drive. Use with caution.",
        "rm": "Deletes a file from the drive. Usage: rm <path>. Use with caution.",
        "drive_details": "Displays the drive details. Usage: drive_details",
        "ed": "Opens a simple file editor. Usage: ed <path>",
        "create": "Creates a new file. Usage: create <path>",
        "paoket": "RASH Package manager. Installs a package, and lists installed packages if called without a package. Usage: paoket [package]",
        "run": "Runs a package. Usage: run <package>",
        "paoketinfo": "Gives information for a Paoket package. Usage: paoketinfo <package>",
        "paoketupdate": "Updates all paoket packages. Usage: paoketupdate"
    }
    alias = {
        "rd": "read",
        "read": "read",
        "testconsole": "testconsole",
        "test": "testconsole",
        "constest": "testconsole",
        "consoletest": "testconsole",
        "wr": "write",
        "write": "write",
        "cat" : "read",
        "help": "help",
        "h": "help",
        "clearconsole": "clearconsole",
        "cls": "clearconsole",
        "clear": "clearconsole",
        "aliases": "aliases",
        "alias": "aliases",
        "echo": "echo",
        "say": "echo",
        "type": "type",
        "math": "math",
        "calc": "math",
        "calculate": "math",
        "python": "python",
        "python3": "python",
        "python2": "python",
        "python1": "python",
        "py": "python",
        "py3": "python",
        "py2": "python",
        "py1": "python",
        "exec": "python",
        "sudo": "sudo",
        "root": "sudo",
        "rashfetch": "rashfetch",
        "fetch": "rashfetch",
        "fastfetch": "rashfetch",
        "cd": "cd",
        "chdir": "cd",
        "ls": "ls",
        "dir": "ls",
        "current_directory": "current_directory",
        "pwd": "current_directory",
        "currdir": "current_directory",
        "curr_dir": "current_directory",
        "format": "format",
        "rm": "rm",
        "remove": "rm",
        "del": "rm",
        "drive_details": "drive_details",
        "drive": "drive_details",
        "ed": "ed",
        "edit": "ed",
        "cr": "create",
        "create": "create",
        "paoket": "paoket",
        "run": "run",
        "r": "run",
        "paoketinfo": "paoketinfo",
        "info": "paoketinfo",
        "paoketupdate": "paoketupdate",
        "update": "paoketupdate"
    }
class Forked():
    def __init__(self, ram = [0] * MEMORY):
        self.SELFRAM = ram
    def execf(self,cmd):
        try:
            command = cmd.split(" ")[0]
            flags = cmd.split(" ")[1:] if len(cmd.split(" ")) > 1 else []
            if command in ROM.alias:
                if ROM.alias[command] in ROM.NEEDS_ELEVATED_PERMS and not PERMS:
                    raise UsrError("Command requires elevated permissions")
                self.SELFRAM = ROM.pin[ROM.alias[command]](flags, self.SELFRAM)
            else:
                raise UsrError(f"Command '{command}' not recognized. Did you mean 'run {command}'")
        except UsrError as e:
            printe("Error: Invalid command or arguments: " + str(e))
        except Exception as e:
            printe("Error: (Internal error): " + str(e))
    def merge(self):
        return self.SELFRAM

def main():
    printf(WELCOME_MSG)
    RUNNING = True
    iter = 0
    RAM = [0] * MEMORY
    while RUNNING:
        iter += 1
        user_input = input("Enter a command (type 'exit' to quit): " if iter == 1 else (f"root@{CURR_DIR}> " if PERMS else f"{USR}@{CURR_DIR}> "))
        if user_input.lower() == 'exit':
            RUNNING = False
            print("Exiting...")
        elif user_input.lower() == 'exitandclear':
            RUNNING = False
            ROM.clearconsole([], [])
        elif user_input.lower() == 'sjelter':
            printf("Sjelter?")
        elif user_input != "":
            fork = Forked(RAM)
            fork.execf(user_input)
            RAM = fork.merge()
            fork.SELFRAM = None


if __name__ == "__main__":
    main()
    